variable "REGISTRY" {
  default = "ghcr.io/nishit-g"
}

variable "VERSION" {
  default = "latest" // You could also get this from an env var for more flexibility
}

// A "default" group that ALL targets will inherit from.
// This is where you define things ONCE.
group "default" {
  platforms = ["linux/amd64"]
  tags = ["${REGISTRY}/aiclipse-${target.name}:${VERSION}"]
  # Push all tags generated by default
  # Add labels, etc. here as well.
}

// Base images
target "base-common" {
  inherits = ["default"] // Inherit platforms and tags
  dockerfile = "base/common.dockerfile"
  context = "."
  contexts = {
    manifests = "./manifests"
  }
}

target "base-rtx4090" {
  inherits = ["default"]
  dockerfile = "base/rtx4090.dockerfile"
  context = "."
  contexts = {
    scripts = "./base/scripts"
    manifests = "./manifests"
  }
  args = {
    BASE_IMAGE = "${REGISTRY}/aiclipse-base-common:${VERSION}"
  }
}

target "base-rtx5090" {
  inherits = ["default"]
  dockerfile = "base/rtx5090.dockerfile"
  context = "."
  contexts = {
    scripts = "./base/scripts"
    manifests = "./manifests"
  }
  args = {
    BASE_IMAGE = "${REGISTRY}/aiclipse-base-common:${VERSION}"
  }
}

// SD 1.5 Basic Template builds
target "sd15-basic-4090" {
  inherits = ["default"]
  // Override the default tag to match your desired naming scheme
  tags = ["${REGISTRY}/aiclipse-sd15-basic:rtx4090-${VERSION}"]
  dockerfile = "Dockerfile"
  context = "templates/sd15-basic"
  args = {
    BASE_IMAGE = "${REGISTRY}/aiclipse-base-rtx4090:${VERSION}"
  }
}

target "sd15-basic-5090" {
  inherits = ["default"]
  tags = ["${REGISTRY}/aiclipse-sd15-basic:rtx5090-${VERSION}"]
  dockerfile = "Dockerfile"
  context = "templates/sd15-basic"
  args = {
    BASE_IMAGE = "${REGISTRY}/aiclipse-base-rtx5090:${VERSION}"
  }
}
