name: 'Setup Docker Build Environment'
description: 'Checks out code, frees disk space, sets up Buildx, and logs into GHCR'

inputs:
  gh_token:
    description: 'GitHub token for GHCR login'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Free up disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false # Important: Keep Docker's local layer cache
        swap-storage: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:buildx-stable-1
          restart-policy=no

    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.gh_token }}
