name: 'Setup Docker Build Environment'
description: 'Checks out code, frees disk space, sets up Buildx, and logs into GHCR'

inputs:
  gh_token:
    description: 'GitHub token for GHCR login'
    required: true

runs:
  using: 'composite'
  steps:
    - name: ⚡ Fast Disk Cleanup
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/node_modules
        sudo rm -rf /usr/share/swift
        sudo rm -rf /opt/hostedtoolcache/CodeQL

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:buildx-stable-1
          restart-policy=no

    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.gh_token }}
