sd15:
  type: checkpoints
  source: huggingface
  repo_id: runwayml/stable-diffusion-v1-5
  filename: v1-5-pruned.safetensors
  save_as: v1-5-pruned.safetensors

realCartoon:
  type: checkpoints
  source: civitai
  url: "https://civitai.com/api/download/models/671503?type=Model&format=SafeTensor&size=pruned&fp=fp16"
  save_as: realcartoonRealistic_v17.safetensors

dreamshaper:
  type: checkpoints
  source: civitai
  url: "https://civitai.com/api/download/models/128713?type=Model&format=SafeTensor&size=pruned&fp=fp16"
  save_as: dreamshaper_8.safetensors

baddream_embeddings:
  type: embeddings
  source: civitai
  url: "https://civitai.com/api/download/models/77169?type=Model&format=PickleTensor"
  save_as: BadDream.pt

lcm_lora:
  type: loras
  source: huggingface
  repo_id: latent-consistency/lcm-lora-sdv1-5
  filename: pytorch_lora_weights.safetensors
  save_as: lcm_15_lora.safetensors

3d_redmond:
  type: loras
  source: civitai
  model_id: 208422
  version_id: 234720
  save_as: 3DRedmond15V.safetensors


sd15-ctrl-inpaint:
  type: controlnet
  source: huggingface
  repo_id: lllyasviel/control_v11p_sd15_inpaint
  filename: diffusion_pytorch_model.fp16.safetensors
  save_as: control_v11p_sd15_inpaint_fp16.safetensors

clip_vit_h:
  type: clip_vision
  source: huggingface
  repo_id: h94/IP-Adapter
  filename: models/image_encoder/model.safetensors
  save_as: CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors

clip_vit_bigG:
  type: clip_vision
  source: huggingface
  repo_id: laion/CLIP-ViT-bigG-14-laion2B-39B-b160k
  filename: open_clip_pytorch_model.bin
  save_as: CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors

# IP-Adapter Models for SD1.5
ip_adapter_basic:
  type: ipadapter
  source: huggingface
  repo_id: h94/IP-Adapter
  filename: models/ip-adapter_sd15.safetensors
  save_as: ip-adapter_sd15.safetensors

ip_adapter_light:
  type: ipadapter
  source: huggingface
  repo_id: h94/IP-Adapter
  filename: models/ip-adapter_sd15_light_v11.bin
  save_as: ip-adapter_sd15_light_v11.bin

ip_adapter_plus:
  type: ipadapter
  source: huggingface
  repo_id: h94/IP-Adapter
  filename: models/ip-adapter-plus_sd15.safetensors
  save_as: ip-adapter-plus_sd15.safetensors

ip_adapter_plus_face:
  type: ipadapter
  source: huggingface
  repo_id: h94/IP-Adapter
  filename: models/ip-adapter-plus-face_sd15.safetensors
  save_as: ip-adapter-plus-face_sd15.safetensors

ip_adapter_full_face:
  type: ipadapter
  source: huggingface
  repo_id: h94/IP-Adapter
  filename: models/ip-adapter-full-face_sd15.safetensors
  save_as: ip-adapter-full-face_sd15.safetensors

ip_adapter_vit_g:
  type: ipadapter
  source: huggingface
  repo_id: h94/IP-Adapter
  filename: models/ip-adapter_sd15_vit-G.safetensors
  save_as: ip-adapter_sd15_vit-G.safetensors
