"""
Model path configuration for ComfyUI.

Creates extra_model_paths.yaml to tell ComfyUI where to find models.
"""

from pathlib import Path
from typing import Optional


# All model types ComfyUI supports
MODEL_TYPES = [
    "checkpoints",
    "diffusion_models",
    "unet",
    "vae", 
    "loras",
    "text_encoders",
    "clip",
    "controlnet",
    "upscale_models",
    "embeddings",
    "hypernetworks",
    "clip_vision",
    "style_models",
    "gligen",
]


def setup_model_paths(
    comfy_dir: str | Path,
    models_dir: str | Path,
    name: str = "aiclipse",
) -> Path:
    """
    Create extra_model_paths.yaml for ComfyUI.
    
    Args:
        comfy_dir: ComfyUI installation directory (where main.py is)
        models_dir: Directory containing model subdirectories
        name: Configuration section name
    
    Returns:
        Path to created yaml file
    """
    comfy_dir = Path(comfy_dir)
    models_dir = Path(models_dir)
    
    yaml_path = comfy_dir / "extra_model_paths.yaml"
    
    # Debug: show what's in the models directory
    print(f"\n📦 Configuring model paths from: {models_dir}")
    
    if models_dir.exists():
        for subdir in sorted(models_dir.iterdir()):
            if subdir.is_dir():
                files = list(subdir.glob("*"))
                real_files = [f for f in files if not f.name.startswith(".")]
                if real_files:
                    print(f"   ✅ {subdir.name}/: {len(real_files)} file(s)")
                else:
                    print(f"   📁 {subdir.name}/: (empty)")
    
    # Build YAML config
    # NOTE: diffusion_models includes unet/ as additional path
    config = f"""# Auto-generated by AiClipse v3
# This tells ComfyUI to look for additional models
{name}:
    base_path: {models_dir}
    checkpoints: checkpoints/
    diffusion_models: |
        diffusion_models/
        unet/
    unet: unet/
    vae: vae/
    loras: loras/
    text_encoders: text_encoders/
    clip: clip/
    controlnet: controlnet/
    upscale_models: upscale_models/
    embeddings: embeddings/
    hypernetworks: hypernetworks/
    clip_vision: clip_vision/
    style_models: style_models/
    gligen: gligen/
"""
    
    yaml_path.write_text(config)
    print(f"✅ Created {yaml_path}")
    
    return yaml_path


def ensure_model_dirs(models_dir: str | Path) -> None:
    """Create all expected model subdirectories."""
    models_dir = Path(models_dir)
    
    for model_type in MODEL_TYPES:
        (models_dir / model_type).mkdir(parents=True, exist_ok=True)
